version: '3.8'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'

  php:
    build:
      context: .
      dockerfile: docker/build/php/Dockerfile
    volumes:
      - ${APP_FOLDER}:/var/www/html
    ports:
      - '80:80'
    